/**
 * Generated model data
 *
 * This file is auto-generated by the scraper scripts.
 * Do not edit manually - your changes will be overwritten.
 *
 * To regenerate, run: npm run scrape
 */

import type { ModelInfo } from '@aeye/ai';

export const awsModels: ModelInfo[] = [{
  id: 'stability.stable-fast-upscale-v1:0',
  provider: 'aws',
  name: 'Stable Image Fast Upscale',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-fast-upscale-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'anthropic.claude-sonnet-4-20250514-v1:0',
  provider: 'aws',
  name: 'Claude Sonnet 4',
  contextWindow: 200000,
  maxOutputTokens: 16384,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {
    text: {
      input: 3,
      output: 15
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-sonnet-4-20250514-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-haiku-4-5-20251001-v1:0',
  provider: 'aws',
  name: 'Claude Haiku 4.5',
  contextWindow: 200000,
  maxOutputTokens: 16384,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {
    text: {
      input: 1,
      output: 5
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-haiku-4-5-20251001-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'stability.stable-image-erase-object-v1:0',
  provider: 'aws',
  name: 'Stable Image Erase Object',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-image-erase-object-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'qwen.qwen3-235b-a22b-2507-v1:0',
  provider: 'aws',
  name: 'Qwen3 235B A22B 2507',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/qwen.qwen3-235b-a22b-2507-v1:0",
    providerName: "Qwen",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'stability.stable-image-control-structure-v1:0',
  provider: 'aws',
  name: 'Stable Image Control Structure',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-image-control-structure-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'openai.gpt-oss-120b-1:0',
  provider: 'aws',
  name: 'gpt-oss-120b',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/openai.gpt-oss-120b-1:0",
    providerName: "OpenAI",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-sonnet-4-5-20250929-v1:0',
  provider: 'aws',
  name: 'Claude Sonnet 4.5',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {
    text: {
      input: 3,
      output: 15
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-sonnet-4-5-20250929-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'stability.stable-creative-upscale-v1:0',
  provider: 'aws',
  name: 'Stable Image Creative Upscale',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-creative-upscale-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'stability.stable-outpaint-v1:0',
  provider: 'aws',
  name: 'Stable Image Outpaint',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-outpaint-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'stability.stable-image-inpaint-v1:0',
  provider: 'aws',
  name: 'Stable Image Inpaint',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-image-inpaint-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'anthropic.claude-opus-4-1-20250805-v1:0',
  provider: 'aws',
  name: 'Claude Opus 4.1',
  contextWindow: 200000,
  maxOutputTokens: 16384,
  tier: 'flagship',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {
    text: {
      input: 15,
      output: 75
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-opus-4-1-20250805-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'amazon.nova-pro-v1:0',
  provider: 'aws',
  name: 'Nova Pro',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.nova-pro-v1:0",
    providerName: "Amazon",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE",
      "VIDEO"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'stability.stable-image-remove-background-v1:0',
  provider: 'aws',
  name: 'Stable Image Remove Background',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-image-remove-background-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'qwen.qwen3-coder-480b-a35b-v1:0',
  provider: 'aws',
  name: 'Qwen3 Coder 480B A35B Instruct',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/qwen.qwen3-coder-480b-a35b-v1:0",
    providerName: "Qwen",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'stability.stable-image-style-guide-v1:0',
  provider: 'aws',
  name: 'Stable Image Style Guide',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-image-style-guide-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'stability.stable-image-control-sketch-v1:0',
  provider: 'aws',
  name: 'Stable Image Control Sketch',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-image-control-sketch-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'stability.stable-conservative-upscale-v1:0',
  provider: 'aws',
  name: 'Stable Image Conservative Upscale',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-conservative-upscale-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'stability.stable-image-search-recolor-v1:0',
  provider: 'aws',
  name: 'Stable Image Search and Recolor',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-image-search-recolor-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'twelvelabs.pegasus-1-2-v1:0',
  provider: 'aws',
  name: 'Pegasus v1.2',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/twelvelabs.pegasus-1-2-v1:0",
    providerName: "TwelveLabs",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "VIDEO"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'stability.stable-style-transfer-v1:0',
  provider: 'aws',
  name: 'Stable Image Style Transfer',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-style-transfer-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'cohere.embed-v4:0',
  provider: 'aws',
  name: 'Embed v4',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['embedding']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/cohere.embed-v4:0",
    providerName: "Cohere",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "EMBEDDING"
    ]
  }
}, {
  id: 'deepseek.v3-v1:0',
  provider: 'aws',
  name: 'DeepSeek-V3.1',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/deepseek.v3-v1:0",
    providerName: "DeepSeek",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'stability.stable-image-search-replace-v1:0',
  provider: 'aws',
  name: 'Stable Image Search and Replace',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['image']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/stability.stable-image-search-replace-v1:0",
    providerName: "Stability AI",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "IMAGE"
    ]
  }
}, {
  id: 'qwen.qwen3-coder-30b-a3b-v1:0',
  provider: 'aws',
  name: 'Qwen3-Coder-30B-A3B-Instruct',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/qwen.qwen3-coder-30b-a3b-v1:0",
    providerName: "Qwen",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'qwen.qwen3-32b-v1:0',
  provider: 'aws',
  name: 'Qwen3 32B (dense)',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/qwen.qwen3-32b-v1:0",
    providerName: "Qwen",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'openai.gpt-oss-20b-1:0',
  provider: 'aws',
  name: 'gpt-oss-20b',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/openai.gpt-oss-20b-1:0",
    providerName: "OpenAI",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'amazon.titan-embed-text-v2:0',
  provider: 'aws',
  name: 'Titan Text Embeddings V2',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['embedding']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.titan-embed-text-v2:0",
    providerName: "Amazon",
    responseStreamingSupported: false,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "EMBEDDING"
    ]
  }
}, {
  id: 'amazon.nova-premier-v1:0:8k',
  provider: 'aws',
  name: 'Nova Premier',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.nova-premier-v1:0:8k",
    providerName: "Amazon",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [],
    inputModalities: [
      "TEXT",
      "IMAGE",
      "VIDEO"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'amazon.nova-premier-v1:0:20k',
  provider: 'aws',
  name: 'Nova Premier',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.nova-premier-v1:0:20k",
    providerName: "Amazon",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [],
    inputModalities: [
      "TEXT",
      "IMAGE",
      "VIDEO"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'amazon.nova-premier-v1:0:1000k',
  provider: 'aws',
  name: 'Nova Premier',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.nova-premier-v1:0:1000k",
    providerName: "Amazon",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [],
    inputModalities: [
      "TEXT",
      "IMAGE",
      "VIDEO"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'amazon.nova-premier-v1:0:mm',
  provider: 'aws',
  name: 'Nova Premier',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.nova-premier-v1:0:mm",
    providerName: "Amazon",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [],
    inputModalities: [
      "TEXT",
      "IMAGE",
      "VIDEO"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'amazon.nova-premier-v1:0',
  provider: 'aws',
  name: 'Nova Premier',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.nova-premier-v1:0",
    providerName: "Amazon",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE",
      "VIDEO"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'amazon.nova-lite-v1:0',
  provider: 'aws',
  name: 'Nova Lite',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.nova-lite-v1:0",
    providerName: "Amazon",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE",
      "VIDEO"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'amazon.nova-micro-v1:0',
  provider: 'aws',
  name: 'Nova Micro',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/amazon.nova-micro-v1:0",
    providerName: "Amazon",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-3-5-sonnet-20240620-v1:0',
  provider: 'aws',
  name: 'Claude 3.5 Sonnet',
  contextWindow: 200000,
  maxOutputTokens: 8192,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {
    text: {
      input: 3,
      output: 15
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-5-sonnet-20240620-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-3-7-sonnet-20250219-v1:0',
  provider: 'aws',
  name: 'Claude 3.7 Sonnet',
  contextWindow: 200000,
  maxOutputTokens: 8192,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {
    text: {
      input: 3,
      output: 15
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-7-sonnet-20250219-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-3-haiku-20240307-v1:0:200k',
  provider: 'aws',
  name: 'Claude 3 Haiku',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-haiku-20240307-v1:0:200k",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-3-haiku-20240307-v1:0',
  provider: 'aws',
  name: 'Claude 3 Haiku',
  contextWindow: 200000,
  maxOutputTokens: 4096,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {
    text: {
      input: 0.25,
      output: 1.25
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-haiku-20240307-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
  provider: 'aws',
  name: 'Claude 3.5 Sonnet v2',
  contextWindow: 200000,
  maxOutputTokens: 8192,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {
    text: {
      input: 3,
      output: 15
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-3-5-haiku-20241022-v1:0',
  provider: 'aws',
  name: 'Claude 3.5 Haiku',
  contextWindow: 200000,
  maxOutputTokens: 8192,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'tools']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'anthropic.claude-opus-4-20250514-v1:0',
  provider: 'aws',
  name: 'Claude Opus 4',
  contextWindow: 200000,
  maxOutputTokens: 16384,
  tier: 'flagship',
  capabilities: new Set(['chat', 'streaming', 'vision', 'tools']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-opus-4-20250514-v1:0",
    providerName: "Anthropic",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'deepseek.r1-v1:0',
  provider: 'aws',
  name: 'DeepSeek-R1',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set([]),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/deepseek.r1-v1:0",
    providerName: "DeepSeek",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'mistral.pixtral-large-2502-v1:0',
  provider: 'aws',
  name: 'Pixtral Large (25.02)',
  contextWindow: 0,
  tier: 'flagship',
  capabilities: new Set(['chat', 'streaming', 'vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/mistral.pixtral-large-2502-v1:0",
    providerName: "Mistral AI",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-1-8b-instruct-v1:0:128k',
  provider: 'aws',
  name: 'Llama 3.1 8B Instruct',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-1-8b-instruct-v1:0:128k",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-1-8b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 3.1 8B Instruct',
  contextWindow: 128000,
  maxOutputTokens: 2048,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming']),
  pricing: {
    text: {
      input: 0.3,
      output: 0.6
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-1-8b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-1-70b-instruct-v1:0:128k',
  provider: 'aws',
  name: 'Llama 3.1 70B Instruct',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-1-70b-instruct-v1:0:128k",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-1-70b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 3.1 70B Instruct',
  contextWindow: 128000,
  maxOutputTokens: 2048,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming']),
  pricing: {
    text: {
      input: 2.65,
      output: 3.5
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-1-70b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-1-405b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 3.1 405B Instruct',
  contextWindow: 128000,
  maxOutputTokens: 4096,
  tier: 'flagship',
  capabilities: new Set(['chat', 'streaming']),
  pricing: {
    text: {
      input: 5.32,
      output: 16
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-1-405b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-2-11b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 3.2 11B Instruct',
  contextWindow: 128000,
  maxOutputTokens: 2048,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision']),
  pricing: {
    text: {
      input: 0.35,
      output: 0.35
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-2-11b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-2-90b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 3.2 90B Instruct',
  contextWindow: 128000,
  maxOutputTokens: 2048,
  tier: 'flagship',
  capabilities: new Set(['chat', 'streaming', 'vision']),
  pricing: {
    text: {
      input: 2.65,
      output: 2.65
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-2-90b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-2-1b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 3.2 1B Instruct',
  contextWindow: 128000,
  maxOutputTokens: 2048,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming']),
  pricing: {
    text: {
      input: 0.1,
      output: 0.1
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-2-1b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-2-3b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 3.2 3B Instruct',
  contextWindow: 128000,
  maxOutputTokens: 2048,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming']),
  pricing: {
    text: {
      input: 0.15,
      output: 0.15
    }
  },
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-2-3b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama3-3-70b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 3.3 70B Instruct',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama3-3-70b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "ON_DEMAND",
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama4-scout-17b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 4 Scout 17B Instruct',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama4-scout-17b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}, {
  id: 'meta.llama4-maverick-17b-instruct-v1:0',
  provider: 'aws',
  name: 'Llama 4 Maverick 17B Instruct',
  contextWindow: 0,
  tier: 'efficient',
  capabilities: new Set(['chat', 'streaming', 'vision']),
  pricing: {},
  metadata: {
    modelArn: "arn:aws:bedrock:us-east-2::foundation-model/meta.llama4-maverick-17b-instruct-v1:0",
    providerName: "Meta",
    responseStreamingSupported: true,
    customizationsSupported: [],
    inferenceTypesSupported: [
      "INFERENCE_PROFILE"
    ],
    inputModalities: [
      "TEXT",
      "IMAGE"
    ],
    outputModalities: [
      "TEXT"
    ]
  }
}];
