/**
 * Generated models index
 *
 * This file is auto-generated by the scraper scripts.
 * Do not edit manually - your changes will be overwritten.
 *
 * To regenerate, run: npm run scrape
 */

import type { ModelInfo } from '@aeye/ai';
import { openaiModels } from './openai';
import { openrouterModels } from './openrouter';
import { replicateModels } from './replicate';

export { openaiModels, openrouterModels, replicateModels };

export const models: ModelInfo[] = [
  ...openaiModels,
  ...openrouterModels,
  ...replicateModels,
];
